FROM ubuntu:24.04

ENV DEBIAN_FRONTEND noninteractive
ENV PSRHOME /software

RUN apt-get update &&\
    apt-get install -y --no-install-recommends \
    git \   
    ca-certificates

RUN apt install -y git openssh-server xauth build-essential libfftw3-bin libfftw3-dev libgsl27 libgsl-dev pgplot5 libglib2.0-dev libcfitsio-bin libcfitsio-dev libpng-dev gfortran tcsh autoconf libx11-dev python3-dev python3-numpy python3-pip python3-venv nano vim rsync less

RUN apt-get install -y libtool python3-tk

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1
RUN update-alternatives --install /usr/bin/python  python  /usr/bin/python3.12 1

RUN rm /usr/lib/python3.12/EXTERNALLY-MANAGED
RUN pip install meson meson-python ninja fitsio tqdm pint-pulsar

#######################
# SSH SETUP
#######################

RUN mkdir /var/run/sshd \ 
    && mkdir /root/.ssh \
    && chmod 700 /root/.ssh \
    && ssh-keygen -A \
    && sed -i "s/^.*PasswordAuthentication.*$/PasswordAuthentication no/" /etc/ssh/sshd_config \
    && sed -i "s/^.*X11Forwarding.*$/X11Forwarding yes/" /etc/ssh/sshd_config \
    && sed -i "s/^.*X11UseLocalhost.*$/X11UseLocalhost no/" /etc/ssh/sshd_config \
    && grep "^X11UseLocalhost" /etc/ssh/sshd_config || echo "X11UseLocalhost no" >> /etc/ssh/sshd_config

RUN echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHoA/lZRLybPOle3xpm12j7lwB264eNZgJsB8dJ8pBD/ pmarconep@gmail.com" >> /root/.ssh/authorized_keys

#######################
# TEMPO
#######################
WORKDIR $PSRHOME
RUN git clone https://git.code.sf.net/p/tempo/tempo

RUN rm tempo/obsys.dat

COPY obsys.dat ${PSRHOME}/tempo/

ENV TEMPO=$PSRHOME"/tempo" 
ENV PATH=$PATH:$PSRHOME"/tempo/bin"

WORKDIR $PSRHOME/tempo
RUN ./prepare

RUN ./configure --prefix=$PSRHOME/tempo && \
    make && \
    make install

#######################
# TEMPO2
#######################
WORKDIR $PSRHOME

RUN git clone https://bitbucket.org/psrsoft/tempo2.git

WORKDIR $PSRHOME/tempo2
RUN ./bootstrap

# ADD observatories
RUN cat <<EOF >> T2runtime/observatory/observatories.dat
# IQueye at Gemini observatories
  1820198.199   -5208357.714    -3194851.6       GEMINI_S            gs
  1776362.940   -5026523.140    -3491158.3       CPT                 cpt
  918022.899   -4345980.855      4561981.2       ARO                 aro
EOF

RUN cp -r T2runtime /usr/share/tempo2/
ENV TEMPO2=/usr/share/tempo2/

RUN ./configure --prefix=$PSRHOME/tempo2
RUN make && make install
RUN make plugins && make plugins-install

ENV PATH=$PSRHOME/tempo2/bin:$PATH

#######################
# PSRCHIVE
#######################
WORKDIR $PSRHOME

RUN git clone git://git.code.sf.net/p/psrchive/code psrchive

WORKDIR $PSRHOME/psrchive

RUN ./bootstrap && \
    ./configure --prefix=$PSRHOME/psrchive && \
    make && \
    make check && \
    make install

#######################
# PRESTO
#######################
WORKDIR $PSRHOME

RUN git clone https://github.com/pmarconep/presto_uchile.git presto5

WORKDIR $PSRHOME/presto5

ENV PGPLOT_DIR="/usr/lib/pgplot5" \
    PGPLOT_FONT="/usr/lib/pgplot5/grfont.dat" \
    PGPLOT_INCLUDES="/usr/include" \
    PGPLOT_BACKGROUND="white" \
    PGPLOT_FOREGROUND="black" \
    PGPLOT_DEV="/xs"

ENV PRESTO="/software/presto5"
ENV PATH="${PRESTO}/installation/bin:${PATH}"
ENV LIBRARY_PATH=${PRESTO}/installation/lib/x86_64-linux-gnu:${LIBRARY_PATH}
ENV LD_LIBRARY_PATH=${PRESTO}/installation/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}

WORKDIR $PSRHOME/presto5

RUN meson setup build --prefix=/software/presto5/installation
RUN python check_meson_build.py
RUN meson compile -C build
RUN meson install -C build

WORKDIR ${PRESTO}/python
RUN pip install --config-settings=builddir=build .

WORKDIR ${PRESTO}/src
RUN ${PRESTO}/build/src/makewisdom
RUN mv  ${PRESTO}/src/fftw_wisdom.txt ${PRESTO}/lib

RUN echo 'export PS1="\[\e[4;30m\]\u@\h\[\e[0m\]:\[\e[1;10m\]\w\[\e[0m\]\$ (docker)> "' >> ~/.bashrc
RUN echo 'alias ls="ls --color=auto"'       >> ~/.bashrc
RUN echo 'alias ll="ls -l"'                 >> ~/.bashrc
RUN echo 'alias LL="ls -lL"'                >> ~/.bashrc
RUN echo 'alias lt="ls -lrt --color"'       >> ~/.bashrc
RUN echo 'alias lh="ls -lh --color"'        >> ~/.bashrc
RUN echo 'alias rm="rm -i"'                 >> ~/.bashrc
RUN echo 'alias cp="cp -i"'                 >> ~/.bashrc
RUN echo 'alias mv="mv -i"'                 >> ~/.bashrc
RUN echo 'alias emacs="emacs -nw"'          >> ~/.bashrc

#######################
# FINAL SETUP
#######################

#variable setup for ssh bash
RUN echo '\n# --- PSR software environment ---' >> /root/.bashrc && \
    echo 'export PSRHOME="/software"' >> /root/.bashrc && \
    echo 'export TEMPO="$PSRHOME/tempo"' >> /root/.bashrc && \
    echo 'export PATH="$PATH:$TEMPO/bin"' >> /root/.bashrc && \
    echo '\n# --- PGPLOT environment ---' >> /root/.bashrc && \
    echo 'export PGPLOT_DIR="/usr/lib/pgplot5"' >> /root/.bashrc && \
    echo 'export PGPLOT_FONT="/usr/lib/pgplot5/grfont.dat"' >> /root/.bashrc && \
    echo 'export PGPLOT_INCLUDES="/usr/include"' >> /root/.bashrc && \
    echo 'export PGPLOT_BACKGROUND="white"' >> /root/.bashrc && \
    echo 'export PGPLOT_FOREGROUND="black"' >> /root/.bashrc && \
    echo 'export PGPLOT_DEV="/xs"' >> /root/.bashrc && \
    echo '\n# --- PRESTO environment ---' >> /root/.bashrc && \
    echo 'export PRESTO="/software/presto5"' >> /root/.bashrc && \
    echo 'export PATH="$PRESTO/installation/bin:$PATH"' >> /root/.bashrc && \
    echo 'export LIBRARY_PATH="$PRESTO/installation/lib/x86_64-linux-gnu:$LIBRARY_PATH"' >> /root/.bashrc && \
    echo 'export LD_LIBRARY_PATH="$PRESTO/installation/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"' >> /root/.bashrc && \
    echo 'export TEMPO2=/usr/share/tempo2/' >>  /root/.bashrc && \
    echo 'export PATH=$PSRHOME/tempo2/bin:$PATH' >> /root/.bashrc && \
    echo 'export PATH=$PSRHOME/psrchive/bin:$PATH' >> /root/.bashrc && \
    echo "export PS1='\[\e[93m\](\[\e[1m\]\!\[\e[22m\])\[\e[0;1m\] \[\e[38;5;124m\]presto_dock:\[\e[38;5;70m\]\w\[\e[38;5;39m\]\$\[\e[0m\] '" >> /root/.bashrc


WORKDIR ${PSRHOME}

ENTRYPOINT ["sh", "-c", "/usr/sbin/sshd && tail -f /dev/null"]